services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ppp-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - sql_server_data:/var/opt/mssql
    healthcheck:
      # This command checks if port 1433 is listening using bash's built-in /dev/tcp
      # It will return 0 if connection is successful, non-zero otherwise.
      test: ["CMD", "bash", "-c", "(echo > /dev/tcp/localhost/1433) >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s  # This check is very fast
      retries: 20
      start_period: 20s

  db-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: ppp-db-init
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./sql_db_init:/init
    command: ["/opt/mssql-tools/bin/sqlcmd", "-S", "db", "-U", "sa", "-P", "${SA_PASSWORD}", "-i", "/init/01-init.sql"]
    restart: "on-failure"

  dataloader:
    build:
      context: .
      dockerfile: src/DataLoader/Dockerfile
    container_name: ppp-dataloader
    depends_on:
      db-init:
        condition: service_completed_successfully
    environment:
      ConnectionStrings__PppDb: "Server=db,1433;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
    command: ["dotnet", "DataLoader.dll"]

  functions-api:
    build:
      context: .
      dockerfile: src/FunctionsApi/Dockerfile
    container_name: ppp-functions-api
    depends_on:
      dataloader:
        condition: service_completed_successfully
    environment:
      ConnectionStrings__PppDb: "Server=db,1433;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
    ports:
      - "7071:80"

volumes:
  sql_server_data:
